set-option -g default-shell /bin/bash
set-option -g default-command '/bin/bash -i'
set -g @shell_mode 'vi'

# tmuxを256色表示できるようにする
set-option -g default-terminal xterm-256color

set-option -g base-index 1

# マウス操作を有効にする
set-option -g mouse on

set-option -g focus-events on

# escapeが押されたときに10msだけ待つ
# (デフォルトは500msだが、これだとnvimでエラーが出る)
set-option -sg escape-time 10

# スクロールバッファの行数を10000行にする
set-option -g history-limit 10000

# ------------------------------
# key bindings
# ------------------------------
# 設定ファイルの再読込
bind r source-file ~/.config/tmux/tmux.conf
# Syncronize on
bind e set-window-option synchronize-panes on
# Synchronize off
bind E set-window-option synchronize-panes off

# ------------------------------
# Copy mode settings
# ------------------------------
# コピーモードでvimキーバインドを使う
setw -g mode-keys vi
# コピーモード中に Vim 風に v で選択範囲を定める
bind -Tcopy-mode-vi v send -X begin-selection
# コピーモード中に Vim 風に y で選択範囲をヤンクしてコピーモードを終了する
bind -Tcopy-mode-vi y send -X copy-pipe-and-cancel
# マウスをドラッグして選択範囲を定め、それをヤンクしてコピーモードを終了する
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel

# ------------------------------
# Plugins
# ------------------------------
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g status-position top
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g status-left ""

set -g @plugin 'tmux-plugins/tmux-sessionist'

# vimのキーバインドでペインを移動する
set -g @plugin 'tmux-plugins/tmux-pain-control'

# 現在アタッチしているセッションを自動で保存するプラグイン
# 2つペアで使う
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

set -g @continuum-save-interval '1'

# like easy motion in vim
set -g @plugin 'Morantron/tmux-fingers'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
run '~/.local/share/tmux/plugins/tpm/tpm'
