set-option -g default-shell /bin/bash
set-option -g default-command '/bin/bash -i'
set -g @shell_mode 'vi'

# tmux 3.2+ 前提
set-option -g default-terminal tmux-256color
set -as terminal-features ',*:RGB'

set-option -g base-index 1
set-option -g mouse on
set-option -g focus-events on
set-option -sg escape-time 10
set-option -g history-limit 100000

# ------------------------------
# key bindings
# ------------------------------
# 設定ファイルの再読込
bind r source-file ~/.config/tmux/tmux.conf
# Syncronize on
bind e set-option -w synchronize-panes on
# Synchronize off
bind E set-option -w synchronize-panes off
# Popup
bind C-p display-popup -E -w 80% -h 80% "taskdog tui"

# ------------------------------
# Copy mode settings
# ------------------------------
set -w -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel

# ------------------------------
# Plugins
# ------------------------------
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g status-position top
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g status-left ""

set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
run '~/.local/share/tmux/plugins/tpm/tpm'
